### ISSUE TITLE
GitHub actions seem to have a race condition

### ISSUE THREAD

**Issue by jradtilbrook** [jradtilbrook/terraform-provider-buildkite#10]
Release v0.0.3 uploaded the windows binary in place of the Mac build. It seems like it's a race condition between the containers running from GitHub actions. The linux build worked fine probably because it ran first/fastest but the Windows/Mac built at the same time and clobbered each others.

I didn't realise they shared the exact same working copy of the repo. That's probably the only explanation.

It's also frustratingly slow so maybe look into either Go releaser or using travis to build things on tagged builds

**Comment by acaire** [comment]
Solved in #11
