### ISSUE TITLE
Error when creating new pipelines

### ISSUE THREAD

**Issue by twelvelabs** [jradtilbrook/terraform-provider-buildkite#31]
Steps to reproduce:

```
resource "buildkite_pipeline" "example" {
  name = "example"
  repository = "git@github.com:example/example.git"
  steps = "steps:\n  - command: \"buildkite-agent pipeline upload\"\n    label: \":pipeline:\""
}
```

Then run `terraform apply`. It should error with:

```
Error: Please ensure at least one team is added to this pipeline
```

I assume this is blocked by #21. Is there some sort of BuildKite config setting that is preventing this from being an issue for other users?

**Comment by jradtilbrook** [comment]
I believe there must be something on the Buildkite end that allows me to continue using it. I haven't had any such issues. I wonder if its related to an old API token I am already using. I plan to get to #21 very soon anyway

**Comment by darrylb-github** [comment]
FYI This also happens on buildkite's own CLI `bk init` https://github.com/buildkite/cli/issues/41

If you're an admin level user it apparently works.

**Comment by yob** [comment]
>  believe there must be something on the Buildkite end that allows me to continue using it. I haven't had any such issues. I wonder if its related to an old API token I am already using. I plan to get to #21 very soon anyway

@jradtilbrook are you an org admin on Buildkite? org admins are able to create new pipelines that belong to no team, but non admins cannot.
