### ISSUE TITLE
v0.0.10 release exec format error

### ISSUE THREAD

**Issue by darrylb-github** [jradtilbrook/terraform-provider-buildkite#49]
Hey @jradtilbrook ,

On the new release v0.0.10, I'm getting `exec format error` when trying to use `terraform-provider-buildkite_v0.0.10_linux_amd64.tar.gz` within a linux docker container. Perhaps it's built / labeled the wrong platform as the linux copy or maybe I'm doing something daft?

```
FROM python:3.7.3-slim
...
RUN curl -o ${plugin_dir}/terraform-provider-buildkite_v0.0.10 -sL https://github.com/jradtilbrook/terraform-provider-buildkite/releases/download/v0.0.10/terraform-provider-buildkite_v0.0.10_linux_amd64.tar.gz && \
    chmod +x ${plugin_dir}/terraform-provider-buildkite_v0.0.10
```

This works pointing at my own manual release https://github.com/darrylb-github/terraform-provider-buildkite/releases/tag/v0.0.9, though I noticed mine is much larger than yours so maybe I did something different building.

**Comment by jradtilbrook** [comment]
Hey @darrylb-github!

It looks to me like you aren't unpacking the tarball before setting permissions, etc. So you're trying to execute the tarball directly instead of its contents?

**Comment by darrylb-github** [comment]
🤦 Did a lazy switch out with my non-tar release and didn't spot it

Thanks
