### ISSUE TITLE
Q: How to set branch filtering?

### ISSUE THREAD

**Issue by runlevel5** [jradtilbrook/terraform-provider-buildkite#53]
I could not find any reference to branch filter in the source code. Wondering if it is possible to set branch filter? cc @jradtilbrook 

![Screenshot_2020-07-29 Settings · admin-ui](https://user-images.githubusercontent.com/135605/88753999-ec70a800-d1a0-11ea-9658-8db48abef1a8.png)

**Comment by jradtilbrook** [comment]
Hi @runlevel5, this provider doesn't currently support that setting. I'm happy to review and accept a PR though if you wanted to add it!

**Comment by runlevel5** [comment]
@jradtilbrook I am new to Golang ..however I could try if you are okay with giving me feedback on my PR.

**Comment by jradtilbrook** [comment]
> @jradtilbrook I am new to Golang ..however I could try if you are okay with giving me feedback on my PR.

Absolutely! If you're willing to give it a go I'll give as much feedback as I can :+1:

**Comment by runlevel5** [comment]
@jradtilbrook https://github.com/jradtilbrook/terraform-provider-buildkite/pull/54
