### ISSUE TITLE
Publish this provider to the terraform registry

### ISSUE THREAD

**Issue by jack1902** [jradtilbrook/terraform-provider-buildkite#61]
@jradtilbrook Not sure how active you are but would it be possible to publish this provider to the terraform registry to make it easier to use. If not, i'll fork and publish it myself as this will make it easier to use this provider

https://registry.terraform.io/publish/provider/

**Comment by jradtilbrook** [comment]
I haven't kept up with the recent things happening with terraform but I'm all for publishing it. I'll check it out this weekend

**Comment by jack1902** [comment]
@jradtilbrook sweet, i'm looking to add a new resource to this provider as the base seems to be there with the `client` but just requires the CRUD for the new resources. Adding a provider is fairly easy, i would have added my fork but didn't want to crowd the `buildkite` namespace without checking here first

**Comment by jack1902** [comment]
@jradtilbrook i've created a PR to add a `docs/` folder which can be viewed on the terraform registry. It will make maintaing this provider and adding new things in the future easier
